// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {ImpactSnapshotLog}  from "../src/reference/ImpactSnapshotLog.sol";
import {NO_CORRECTION}      from "../src/interfaces/IImpactSnapshotLog.sol";
import {
    ENERGY_GENERATED, CARBON_OFFSET, BENEFICIARIES,
    UNIT_KWH, UNIT_TCO2E, UNIT_PERSONS
} from "../src/libraries/ImpactConstants.sol";

/// @title  ExampleERC3643ImpactSnapshot
/// @notice Shows ESG impact reporting for a T-REX (ERC-3643) green bond.
///         The bond's EIP-1 anchorId is the subjectId in EIP-4, linking on-chain
///         token compliance (EIP-1), document bundles (EIP-2), and impact data (EIP-4).
///
/// Prerequisites -- run ExampleERC3643Lifecycle.s.sol first (EIP-1 package):
///   export ASSET_ANCHOR_ID=<anchorId from registerAnchor for the bond>
///
/// Run:
///   forge script script/ExampleERC3643ImpactSnapshot.s.sol \
///     --rpc-url $SEPOLIA_RPC_URL \
///     --broadcast -vvvv
///
/// Flow:
///   1. Deploy ImpactSnapshotLog, configure reporter and ESG attestor
///   2. Record annual 2024 impact: energy generated, CO2 offset, beneficiaries
///   3. Independent ESG auditor attests all three snapshots
///   4. Record interim H1 2025 data (partial year)
///   5. Discovery: CO2 offset was overstated -- record a correction
///   6. Show full snapshot history for the bond asset
contract ExampleERC3643ImpactSnapshot is Script {
    // Reporting periods
    uint64 constant Y2024_START  = 1704067200; // 2024-01-01
    uint64 constant Y2024_END    = 1735689600; // 2025-01-01
    uint64 constant H1_2025_START = 1735689600; // 2025-01-01
    uint64 constant H1_2025_END   = 1751328000; // 2025-07-01

    bytes32 constant METH_ICMA_2021 = keccak256("ICMA-GreenBond-Principles-2021");
    string  constant METH_ICMA_URI  = "ipfs://QmICMAGreenBondPrinciples2021";

    function run() external {
        uint256 deployerKey   = vm.envUint("PRIVATE_KEY");
        address deployer      = vm.addr(deployerKey);
        bytes32 assetAnchorId = vm.envBytes32("ASSET_ANCHOR_ID");
        address reporter      = vm.envOr("REPORTER", deployer);
        address esgAuditor    = vm.envOr("ESG_AUDITOR", deployer);

        vm.startBroadcast(deployerKey);

        // 1. Deploy and configure roles
        ImpactSnapshotLog log = new ImpactSnapshotLog(deployer);

        bytes32 reporterRole = log.REPORTER_ROLE();
        bytes32 attestorRole = log.ATTESTOR_ROLE();
        if (reporter   != deployer) { log.grantRole(reporterRole, reporter); }
        if (esgAuditor != deployer) { log.grantRole(attestorRole, esgAuditor); }

        console.log("ImpactSnapshotLog:", address(log));
        console.log("Reporting for bond asset:");
        console.logBytes32(assetAnchorId);

        // 2a. Annual 2024 -- energy generated by funded renewable projects (MWh → kWh)
        uint256 energyIdx = log.recordSnapshot(
            assetAnchorId, ENERGY_GENERATED,
            3_200_000_000, 0, UNIT_KWH, // 3,200,000 MWh expressed in kWh
            Y2024_START, Y2024_END,
            METH_ICMA_2021, METH_ICMA_URI,
            NO_CORRECTION
        );
        console.log("2024 ENERGY_GENERATED index:", energyIdx);

        // 2b. Annual 2024 -- CO2 avoided (tCO2e, 2 decimals → 142300 = 1,423.00 tCO2e)
        uint256 co2Idx = log.recordSnapshot(
            assetAnchorId, CARBON_OFFSET,
            142300, 2, UNIT_TCO2E,
            Y2024_START, Y2024_END,
            METH_ICMA_2021, METH_ICMA_URI,
            NO_CORRECTION
        );
        console.log("2024 CARBON_OFFSET index:", co2Idx);

        // 2c. Annual 2024 -- community beneficiaries from funded projects
        uint256 benIdx = log.recordSnapshot(
            assetAnchorId, BENEFICIARIES,
            12_400, 0, UNIT_PERSONS,
            Y2024_START, Y2024_END,
            METH_ICMA_2021, METH_ICMA_URI,
            NO_CORRECTION
        );
        console.log("2024 BENEFICIARIES index:", benIdx);

        // 3. Independent ESG auditor attests all three annual snapshots
        bytes32 auditEvidence = keccak256("esg-audit-annual-2024-final-report");
        log.attestSnapshot(assetAnchorId, energyIdx, true, auditEvidence, "ipfs://QmESGAudit2024Energy");
        log.attestSnapshot(assetAnchorId, co2Idx,    true, auditEvidence, "ipfs://QmESGAudit2024Carbon");
        log.attestSnapshot(assetAnchorId, benIdx,    true, auditEvidence, "ipfs://QmESGAudit2024Beneficiaries");
        console.log("All 2024 snapshots attested by ESG auditor.");

        // 4. H1 2025 interim report -- energy generated
        uint256 h1EnergyIdx = log.recordSnapshot(
            assetAnchorId, ENERGY_GENERATED,
            1_750_000_000, 0, UNIT_KWH,
            H1_2025_START, H1_2025_END,
            METH_ICMA_2021, METH_ICMA_URI,
            NO_CORRECTION
        );
        console.log("H1 2025 ENERGY_GENERATED index:", h1EnergyIdx);

        // 5. Correction -- 2024 CO2 was overstated due to methodology error
        //    Revised: 138750 (not 142300)
        uint256 co2CorrIdx = log.recordSnapshot(
            assetAnchorId, CARBON_OFFSET,
            138750, 2, UNIT_TCO2E,
            Y2024_START, Y2024_END,
            METH_ICMA_2021, METH_ICMA_URI,
            co2Idx  // correctsIndex
        );
        console.log("2024 CARBON_OFFSET correction index:", co2CorrIdx);

        // 6. Verify correction chain
        uint256 current = log.currentSnapshotForPeriod(assetAnchorId, CARBON_OFFSET, Y2024_START, Y2024_END);
        require(current == co2CorrIdx, "currentSnapshotForPeriod must return corrected snapshot");
        console.log("currentSnapshotForPeriod(CARBON_OFFSET, 2024) =", current, "(corrected)");

        uint256 totalSnapshots = log.snapshotCount(assetAnchorId);
        console.log("Total snapshots for bond asset:", totalSnapshots);

        vm.stopBroadcast();

        console.log("\n== ERC-3643 ESG bond impact summary ==");
        console.log("Three indicators tracked: ENERGY_GENERATED, CARBON_OFFSET, BENEFICIARIES.");
        console.log("2024 annual report attested; CO2 correction chain linked.");
        console.log("EIP-1 anchor ID = EIP-2 subjectId = EIP-4 subjectId.");
        console.log("All three EIP layers reference the same on-chain asset identity.");
    }
}
