// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.24;

// Subject type identifiers
bytes32 constant SUBJECT_TOKEN = keccak256("EIP-XXXX:SUBJECT_TYPE:TOKEN");
bytes32 constant SUBJECT_ADDRESS = keccak256("EIP-XXXX:SUBJECT_TYPE:ADDRESS");
bytes32 constant SUBJECT_ASSET = keccak256("EIP-XXXX:SUBJECT_TYPE:ASSET");
bytes32 constant SUBJECT_CASE = keccak256("EIP-XXXX:SUBJECT_TYPE:CASE");

// Event type identifiers
bytes32 constant EVT_ISSUANCE = keccak256("EIP-XXXX:EVENT_TYPE:ISSUANCE:V1");
bytes32 constant EVT_TRANSFER = keccak256("EIP-XXXX:EVENT_TYPE:TRANSFER:V1");
bytes32 constant EVT_REDEMPTION = keccak256("EIP-XXXX:EVENT_TYPE:REDEMPTION:V1");
bytes32 constant EVT_FREEZE = keccak256("EIP-XXXX:EVENT_TYPE:FREEZE:V1");
bytes32 constant EVT_UNFREEZE = keccak256("EIP-XXXX:EVENT_TYPE:UNFREEZE:V1");
bytes32 constant EVT_FORCED_TRANSFER = keccak256("EIP-XXXX:EVENT_TYPE:FORCED_TRANSFER:V1");
bytes32 constant EVT_KYC_APPROVED = keccak256("EIP-XXXX:EVENT_TYPE:KYC_APPROVED:V1");
bytes32 constant EVT_KYC_REVOKED = keccak256("EIP-XXXX:EVENT_TYPE:KYC_REVOKED:V1");
bytes32 constant EVT_KYC_UPDATED = keccak256("EIP-XXXX:EVENT_TYPE:KYC_UPDATED:V1");
bytes32 constant EVT_REGULATORY_HOLD = keccak256("EIP-XXXX:EVENT_TYPE:REGULATORY_HOLD:V1");
bytes32 constant EVT_HOLD_RELEASED = keccak256("EIP-XXXX:EVENT_TYPE:HOLD_RELEASED:V1");
bytes32 constant EVT_ALLOWLIST_ADDED = keccak256("EIP-XXXX:EVENT_TYPE:ALLOWLIST_ADDED:V1");
bytes32 constant EVT_ALLOWLIST_REMOVED = keccak256("EIP-XXXX:EVENT_TYPE:ALLOWLIST_REMOVED:V1");
bytes32 constant EVT_POLICY_CHANGE = keccak256("EIP-XXXX:EVENT_TYPE:POLICY_CHANGE:V1");
bytes32 constant EVT_CORRECTION = keccak256("EIP-XXXX:EVENT_TYPE:CORRECTION:V1");

// Party role identifiers
bytes32 constant ROLE_SENDER = keccak256("EIP-XXXX:PARTY_ROLE:SENDER");
bytes32 constant ROLE_RECEIVER = keccak256("EIP-XXXX:PARTY_ROLE:RECEIVER");
bytes32 constant ROLE_TARGET = keccak256("EIP-XXXX:PARTY_ROLE:TARGET");
bytes32 constant ROLE_BENEFICIARY = keccak256("EIP-XXXX:PARTY_ROLE:BENEFICIARY");
bytes32 constant ROLE_CONTROLLER = keccak256("EIP-XXXX:PARTY_ROLE:CONTROLLER");
bytes32 constant ROLE_SUBJECT = keccak256("EIP-XXXX:PARTY_ROLE:SUBJECT");

// Outcome identifiers
bytes32 constant OUTCOME_APPROVED = keccak256("EIP-XXXX:OUTCOME:APPROVED");
bytes32 constant OUTCOME_DENIED = keccak256("EIP-XXXX:OUTCOME:DENIED");
bytes32 constant OUTCOME_PENDING = keccak256("EIP-XXXX:OUTCOME:PENDING");
bytes32 constant OUTCOME_EXECUTED = keccak256("EIP-XXXX:OUTCOME:EXECUTED");
bytes32 constant OUTCOME_EXPIRED = keccak256("EIP-XXXX:OUTCOME:EXPIRED");
bytes32 constant OUTCOME_REVOKED = keccak256("EIP-XXXX:OUTCOME:REVOKED");

// Common authority identifiers
bytes32 constant AUTHORITY_INTERNAL_POLICY = keccak256("EIP-XXXX:AUTHORITY:INTERNAL_POLICY:V1");
bytes32 constant AUTHORITY_COURT_ORDER = keccak256("EIP-XXXX:AUTHORITY:COURT_ORDER:V1");
bytes32 constant AUTHORITY_REGULATOR = keccak256("EIP-XXXX:AUTHORITY:REGULATOR:V1");

// Payload profile identifiers
bytes32 constant PAYLOAD_TRANSFER_V1 = keccak256("EIP-XXXX:PAYLOAD:TRANSFER:V1");
bytes32 constant PAYLOAD_FREEZE_V1 = keccak256("EIP-XXXX:PAYLOAD:FREEZE:V1");
bytes32 constant PAYLOAD_KYC_V1 = keccak256("EIP-XXXX:PAYLOAD:KYC:V1");
bytes32 constant PAYLOAD_FORCED_TRANSFER_V1 = keccak256("EIP-XXXX:PAYLOAD:FORCED_TRANSFER:V1");
